### ISSUE TITLE
Data cleaning

### ISSUE THREAD

**Issue by Zenoix** [Zenoix/Anime-Recommendations#1]
A lot of names are duplicates because of formatting.

**Comment by Zenoix** [comment]
https://towardsdatascience.com/fuzzywuzzy-find-similar-strings-within-one-column-in-a-pandas-data-frame-99f6c2a0c212

**Comment by Zenoix** [comment]
https://www.youtube.com/watch?v=ahn-iyQPgpQ

**Comment by Zenoix** [comment]
http://jonathansoma.com/lede/algorithms-2017/classes/fuzziness-matplotlib/fuzzing-matching-in-pandas-with-fuzzywuzzy/

**Comment by Zenoix** [comment]
https://openrefine.org/

**Comment by Zenoix** [comment]
https://www.datacamp.com/community/tutorials/fuzzy-string-python

**Comment by Zenoix** [comment]
https://towardsdatascience.com/fuzzy-matching-at-scale-84f2bfd0c536

**Comment by chandanrajr** [comment]
I want to help you

**Comment by Zenoix** [comment]
> I want to help you

If you'd like to I guess I'm fine with it
